import { Poppins } from 'next/font/google'
import '../styles/globals.css'
import '@fortawesome/fontawesome-free/css/all.min.css'; 

const inter = Poppins({ 
  subsets: ['latin'], 
  weight: ['400', '500', '600', '700', '800'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html style={{scrollBehavior: "smooth"}} lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  )
}
